# Generated by Django 4.0.2 on 2022-02-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='org_detail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='teacher_detail',
        ),
    ]
