# Generated by Django 4.0.2 on 2022-02-24 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_org_detail_remove_user_teacher_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgdetail',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='orgdetail',
            name='mobile_number',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='orgdetail',
            name='org_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='orgdetail',
            name='phone_number',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='orgdetail',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherdetail',
            name='full_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='teacherdetail',
            name='phone_number',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='teacherdetail',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
