# Generated by Django 4.0.2 on 2022-03-07 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_orgdetail_address_orgdetail_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherdetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teacherdetail',
            name='user_id',
        ),
        migrations.AddField(
            model_name='teacherdetail',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
