# Generated by Django 4.0.2 on 2022-03-07 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_teacherdetail_id_remove_teacherdetail_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgdetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='orgdetail',
            name='user_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
