# Generated by Django 4.0.6 on 2022-07-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apps_no',
            field=models.IntegerField(default=0),
        ),
    ]
