# Generated by Django 4.0.6 on 2022-08-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='time',
            field=models.CharField(default='', max_length=55),
        ),
    ]
