# Generated by Django 4.0.6 on 2022-08-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_interview_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(default='active', max_length=16),
        ),
    ]
