# Generated by Django 4.1 on 2022-08-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
