# Generated by Django 4.1 on 2022-08-08 11:44

from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_token_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='feedback.token')),
                ('rating', models.IntegerField(default=1, verbose_name=feedback.models.Token)),
            ],
        ),
    ]
