# Generated by Django 4.0.6 on 2022-07-10 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_rename_user_id_orgdetail_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('intro', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default='', max_length=44)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='', max_length=44)),
                ('level_of_fluency', models.CharField(default='', max_length=44)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=44)),
                ('org', models.CharField(default='', max_length=44)),
                ('start_date_month', models.CharField(default='', max_length=44)),
                ('start_date_year', models.CharField(default='', max_length=44)),
                ('end_date_month', models.CharField(default='', max_length=44)),
                ('end_date_year', models.CharField(default='', max_length=44)),
                ('description', models.TextField(default='')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='', max_length=44)),
                ('field_of_study', models.CharField(default='', max_length=44)),
                ('school', models.CharField(default='', max_length=44)),
                ('schoolLocation', models.CharField(default='', max_length=44)),
                ('start_date_month', models.CharField(default='', max_length=44)),
                ('start_date_year', models.CharField(default='', max_length=44)),
                ('end_date_month', models.CharField(default='', max_length=44)),
                ('end_date_year', models.CharField(default='', max_length=44)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
    ]
