# Generated by Django 4.0.6 on 2022-07-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.TextField(default='44'),
        ),
    ]
