# Generated by Django 4.0.6 on 2022-07-24 17:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_resume_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=44)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=44), size=None)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
    ]
