# Generated by Django 4.1 on 2022-08-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_relsearchconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ranking',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
