# Generated by Django 4.1 on 2022-08-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_resume_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='students',
            field=models.IntegerField(default=0),
        ),
    ]
